#!/usr/bin/env node
// Generates the tiny decode-bench fixtures that are base64-inlined into the client
// (src/bench-data.ts). Re-run only if you want different clips:
//   node scripts/gen-bench.mjs [--ffmpeg /opt/homebrew/bin/ffmpeg]
//
// Clips: H.264 Annex B, 15 frames, IDR at frame 0, no B-frames.
//   720p  -> Constrained Baseline, level 3.1
//   1080p -> Main, level 4.0
// Plus one 1280x720 baseline JPEG for the createImageBitmap bench.
// A simple low-entropy pattern (two moving boxes on a flat field) keeps them small
// (~5-8 KB each) while still exercising motion compensation and deblocking.
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const argi = process.argv.indexOf('--ffmpeg');
const FF = argi > 0 ? process.argv[argi + 1] : (process.env.FFMPEG || '/opt/homebrew/bin/ffmpeg');
const dir = mkdtempSync(join(tmpdir(), 'dashcast-bench-'));

function pattern(w, h) {
  return [
    `color=c=0x16181d:size=${w}x${h}:rate=30`,
    `drawbox=x='mod(t*${Math.round(w * 0.9)},iw-${Math.round(w / 4)})':y=ih/3:w=${Math.round(w / 4)}:h=${Math.round(w / 4)}:color=0x4f8cff:t=fill`,
    `drawbox=x='iw-mod(t*${Math.round(w * 0.55)},iw)':y=ih/8:w=${Math.round(w / 8)}:h=ih*3/4:color=0xff7a45:t=fill`,
  ].join(',');
}

function h264(w, h, profile, level, crf) {
  const out = join(dir, `b${h}.h264`);
  execFileSync(FF, [
    '-hide_banner', '-loglevel', 'error', '-y',
    '-f', 'lavfi', '-i', pattern(w, h),
    '-frames:v', '15',
    '-c:v', 'libx264', '-profile:v', profile, '-level', level,
    '-bf', '0', '-tune', 'zerolatency',
    '-x264-params', 'keyint=15:min-keyint=15:scenecut=0:aud=1',
    '-crf', String(crf), '-pix_fmt', 'yuv420p',
    '-bsf:v', 'h264_mp4toannexb', '-f', 'h264', out,
  ]);
  return stripSEI(readFileSync(out));
}

// Drop SEI NALs (x264 writes its whole settings string there, ~600 B).
function stripSEI(b) {
  const starts = [];
  for (let i = 0; i + 3 < b.length; i++) {
    if (b[i] === 0 && b[i + 1] === 0 && b[i + 2] === 1) {
      starts.push(i > 0 && b[i - 1] === 0 ? i - 1 : i);
      i += 2;
    }
  }
  starts.push(b.length);
  const keep = [];
  for (let k = 0; k + 1 < starts.length; k++) {
    const s = starts[k];
    const hdr = b[s + (b[s + 2] === 1 ? 3 : 4)];
    if ((hdr & 0x1f) !== 6) keep.push(b.subarray(s, starts[k + 1]));
  }
  return Buffer.concat(keep);
}

function jpeg(w, h, q) {
  const out = join(dir, 'b.jpg');
  execFileSync(FF, [
    '-hide_banner', '-loglevel', 'error', '-y',
    '-f', 'lavfi', '-i', pattern(w, h), '-ss', '0.3', '-frames:v', '1',
    '-q:v', String(q), '-pix_fmt', 'yuvj420p', out,
  ]);
  return readFileSync(out);
}

const c720 = h264(1280, 720, 'baseline', '3.1', 30);
const c1080 = h264(1920, 1080, 'main', '4.0', 30);
const j720 = jpeg(1280, 720, 8);
rmSync(dir, { recursive: true, force: true });

const src = `// GENERATED by scripts/gen-bench.mjs — do not edit by hand.
// H.264 Annex B clips (15 frames, IDR first, no B-frames) + one JPEG for the load-time decode bench.
export const H264_720P = '${c720.toString('base64')}';
export const H264_720P_CODEC = 'avc1.42E01F';
export const H264_1080P = '${c1080.toString('base64')}';
export const H264_1080P_CODEC = 'avc1.4D4028';
export const JPEG_720P = '${j720.toString('base64')}';
`;
writeFileSync(join(here, '..', 'src', 'bench-data.ts'), src);
console.log(`720p h264 ${c720.length} B, 1080p h264 ${c1080.length} B, jpeg ${j720.length} B -> src/bench-data.ts (${src.length} chars)`);
